// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFHh199Hih14HzjF8j0KTl-YwWRUBnu2c',
    appId: '1:470073925298:web:e89c097c3cda51154af3ab',
    messagingSenderId: '470073925298',
    projectId: 'cs3130-houndchaserdb',
    authDomain: 'cs3130-houndchaserdb.firebaseapp.com',
    databaseURL: 'https://cs3130-houndchaserdb-default-rtdb.firebaseio.com',
    storageBucket: 'cs3130-houndchaserdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFxkmg3WL4OiXHUqLG0MinPCCZNSjvbIw',
    appId: '1:470073925298:android:ab4c80b54b80cb404af3ab',
    messagingSenderId: '470073925298',
    projectId: 'cs3130-houndchaserdb',
    databaseURL: 'https://cs3130-houndchaserdb-default-rtdb.firebaseio.com',
    storageBucket: 'cs3130-houndchaserdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-0x9Uwb2qxmvIjbhl_AWweXow-e4mDx8',
    appId: '1:470073925298:ios:d96aa0f272eb8f644af3ab',
    messagingSenderId: '470073925298',
    projectId: 'cs3130-houndchaserdb',
    databaseURL: 'https://cs3130-houndchaserdb-default-rtdb.firebaseio.com',
    storageBucket: 'cs3130-houndchaserdb.appspot.com',
    iosBundleId: 'com.example.houndchaserGroupproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-0x9Uwb2qxmvIjbhl_AWweXow-e4mDx8',
    appId: '1:470073925298:ios:6b89d35733c56e234af3ab',
    messagingSenderId: '470073925298',
    projectId: 'cs3130-houndchaserdb',
    databaseURL: 'https://cs3130-houndchaserdb-default-rtdb.firebaseio.com',
    storageBucket: 'cs3130-houndchaserdb.appspot.com',
    iosBundleId: 'com.example.houndchaserGroupproject.RunnerTests',
  );
}
